name: Publish Docker image to Dockerhub
on:
  push:
    branches: master
    tags:
      - "v*"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.repository == 'sudoinclabs/sudo-docker-openvpn'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build OpenVPN Image
        run: |
          docker build -t openvpn .
      - name: Tag, and push image to DockerHub
        run: |
          docker tag openvpn sudoinclabs/openvpn:latest
          docker push --all-tags sudoinclabs/openvpn
      - name: Set Tag name in output
        id: current_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish and release the new version
        env:
          LATEST: ${{ steps.current_tag.outputs.tag }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag openvpn sudoinclabs/openvpn:$LATEST
          docker push --all-tags sudoinclabs/openvpn
      - name: Build SUDO Duo OpenVPN Image
        run: |
          docker build -t sudovpn -f Dockerfile.duo .
      - name: Tag, and push image to DockerHub
        run: |
          docker tag sudovpn sudoinclabs/openvpn:sudovpn-latest
          docker push --all-tags sudoinclabs/openvpn
      - name: Publish and release the new version
        env:
          LATEST: ${{ steps.current_tag.outputs.tag }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag sudovpn sudoinclabs/openvpn:sudovpn-$LATEST
          docker push --all-tags sudoinclabs/openvpn


